apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthy-app
  namespace: kubeassist-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthy-app
  template:
    metadata:
      labels:
        app: healthy-app
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: healthy-app
  namespace: kubeassist-lab
spec:
  selector:
    app: healthy-app
  ports:
    - name: http
      port: 80
      targetPort: 80