apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-demo
  namespace: kubeassist-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-demo
  template:
    metadata:
      labels:
        app: service-demo
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: broken-service
  namespace: kubeassist-lab
spec:
  selector:
    app: wrong-label
  ports:
    - port: 80
      targetPort: 80